from dataclasses import dataclass

import numpy as np
from scipy.special import jv


def um_to_m(x_um):
    return x_um * 1e-6


@dataclass(frozen=True)
class AxiconParams:
    wavelength_nm: float = 650.0
    n: float = 1.457
    alpha_deg: float = 5.0

    @property
    def wavelength_m(self):
        return self.wavelength_nm * 1e-9

    @property
    def alpha_rad(self):
        return np.deg2rad(self.alpha_deg)

    @property
    def k(self):
        return 2 * np.pi / self.wavelength_m

    @property
    def k_r(self):
        # Rao relation: k_r = k sin[(n - 1) alpha]
        return self.k * np.sin((self.n - 1) * self.alpha_rad)

    @property
    def k_r_small_angle(self):
        return self.k * (self.n - 1) * self.alpha_rad

    def check_small_angle_approximation(self):
        relative_error = (self.k_r_small_angle - self.k_r) / self.k_r
        print(f"k = {self.k:.3e} 1/m")
        print(f"k_r = {self.k_r:.3e} 1/m")
        print(f"k_r small-angle approx = {self.k_r_small_angle:.3e} 1/m")
        print(f"relative error = {(self.k_r_small_angle - self.k_r) / self.k_r:.3e}")
        return relative_error

def zmax_axicon(w_um, params: AxiconParams):
    """
    Rao Eq. 3.18:
        zmax = k w / k_r
    """
    return params.k * um_to_m(w_um) / params.k_r


def axial_envelope(z_m, w_um, params: AxiconParams, ell=0):
    zmax = zmax_axicon(w_um, params)
    s = z_m / zmax
    return s**(2 * ell + 1) * np.exp(-2 * s**2)


def radial_profile(r_m, params, ell=0):
    return jv(ell, params.k_r * r_m) ** 2


def bessel_gauss_intensity(
    r_m,
    z_m,
    w_um,
    params: AxiconParams,
    ell=0,
    normalize_peak=True,
):
    """
    Calculate intensity distribution of a Bessel-Gauss beam generated by an axicon.
    Rao Eq. 3.17:
        I_l(r,z) ∝ (z/zmax)^(2l+1) exp[-2 z^2 / zmax^2] J_l^2(k_r r)
    """
    I = axial_envelope(z_m, w_um, params, ell=ell) * radial_profile(
        r_m, params, ell=ell
    )

    if normalize_peak:
        s_peak = np.sqrt((2 * ell + 1) / 4)
        envelope_peak = s_peak**(2 * ell + 1) * np.exp(-2 * s_peak**2)
        I = I / envelope_peak

    return I

